application: siriusflying
version: 3
runtime: go
api_version: go1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /build
  static_dir: build

- url: /.*
  script: _go_app
