application: siriusflying
version: 4
runtime: go
api_version: go1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /fonts
  static_dir: fonts

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /.*
  script: _go_app
