application: siriusflying
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /build
  static_dir: build

- url: /.*
  script: siriusflying.py
