application: siriusflying
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /build
  static_dir: build

- url: /.*
  script: siriusflying.app
